### ISSUE TITLE
Van Time.

### ISSUE THREAD

**Issue by fimars** [KasumiUtako/lidis#1]
Q: TS/JS, 用那个(ts|es)lint方案。 A: 暂时看来是TS多一点，求理由。
Q: 服务端的测试方案选择什么? 目前看来Ava, Jest都不错。
Q: 服务端和客户端是直接http还是上websocket, 或者有更细化的考虑。
Q: Redis这些命令大约分成那几块，现在看来有什么需要注意的吗。 [文档地址](https://redis.io/commands)

**PS: A的话统一编辑自己的那个就好了，不用再往下加**
**PSS: 有问题的话往下面加，保持顺序就可以了**

**Comment by Muzm** [comment]
ts

**Comment by yuxino** [comment]
ts

**Comment by Hazlank** [comment]
ts

**Comment by haozi23333** [comment]
前端ts 后端 js
用websocket，服务端会推送订阅， 比如其他程序修改了数据库
我觉得前端直接向后端eval就好了， 认证完毕之后， 最简单的代理层
@fimars 整个就一个 socket连接， 不管怎么写都比 http的简单

@Nbsaw Redis服务支持订阅数据， 其他程序修改了数据之后更新到管理界面

**Comment by fimars** [comment]
js... 瑟瑟发抖

**Comment by yuxino** [comment]
实时性 其实 没必要吧?

对于频繁更新的服务端来说 ..,

**Comment by fimars** [comment]
@Nbsaw 假设服务端本身有数据更新呢，这个需要做什么细化的操作吗？频繁的服务端来说会怎么样，细化一下。 ❓ 

@haozi23333 就是昊哥说的那个，可以更新客户端信息。可以直接eval，先定一个最小的流程, 然后写test case试试看。

@Hazlank 我现在看来是大部分用http就好了，看看有没有好的方法监听服务端的更新，有的话就加一个websocket。

**Comment by yuxino** [comment]
服务端本身有数据更新是?

**Comment by fimars** [comment]
假设有正在运行的其他应用更新了redis中的数据的情况。

**Comment by Hazlank** [comment]
页面突然更新数据看起来不会很奇怪吗

**Comment by Nbsaw** [comment]
等等 。 为什么其他应用会更新redis中的数据。 redis 可以分好多个数据库的.  每个应用不应该隔离吗.

**Comment by haozi23333** [comment]
@Nbsaw 我们做的是管理系统， 不应该查看实时的信息的吗

**Comment by haozi23333** [comment]
前端的表现风格

**Comment by fimars** [comment]
@haozi23333 前端表现风格暂不讨论

**Comment by yuxino** [comment]
![image](https://user-images.githubusercontent.com/12481935/32880163-98573134-cae7-11e7-9534-a2421fa376aa.png) 

实时信息指的是这边的keys吗?  还是说 其他的?

**Comment by haozi23333** [comment]
@Nbsaw 后端发送到前端， 前端处理 。  keys 不会动态刷新， 只会刷新当前打开的 key的value

**Comment by yuxino** [comment]
@haozi23333 恩 实时

**Comment by fimars** [comment]
@haozi23333 @Muzm @Nbsaw @Hazlank FAQ dead dead next door

**Comment by yuxino** [comment]
奥义很爽
